"""Backend-neutral contracts and utilities for probabilistic regression."""

from probreg.core.checkpoints import Checkpoint, CheckpointStore
from probreg.core.distributions import (
    DistributionHead,
    DistributionLoss,
    Likelihood,
    Loss,
    PredictionLoss,
    PredictiveDistribution,
)
from probreg.core.early_stopping import (
    EarlyStopper,
    EarlyStoppingDecision,
    EarlyStoppingState,
    MetricSource,
    OptimizationMode,
)
from probreg.core.losses import (
    BetaNLLLoss,
    GaussianNLLLoss,
    NegativeLogLikelihoodLoss,
    SquaredErrorLoss,
    add_epsilon,
)
from probreg.core.metric_registry import (
    ContinuousRankedProbabilityScore,
    EpochMetric,
    EpochPredictionData,
    EvaluationGrid,
    IntervalCoverage,
    MetricRequirements,
    PointContinuousRankedProbabilityScore,
    PredictionInterval,
    RootMeanSquaredError,
    WeightedSpread,
)
from probreg.core.metrics import cdf, coverage, crps, point_crps, rmse, wsu
from probreg.core.protocols import (
    Dataset,
    LoaderFactory,
    Optimizer,
    Step,
    ValidationStrategy,
)
from probreg.core.stages import StageState, TrainingStage, validate_transition
from probreg.core.tracking import EventSink, ExperimentTracker, TrainingEvent
from probreg.core.types import (
    Array,
    Batch,
    CheckpointRef,
    ParameterRole,
    PyTree,
    StageResult,
    TrainingState,
    ValidationResult,
)

__all__ = [
    "Array",
    "Batch",
    "BetaNLLLoss",
    "Checkpoint",
    "CheckpointRef",
    "CheckpointStore",
    "ContinuousRankedProbabilityScore",
    "Dataset",
    "DistributionHead",
    "DistributionLoss",
    "EarlyStopper",
    "EarlyStoppingDecision",
    "EarlyStoppingState",
    "EpochMetric",
    "EpochPredictionData",
    "EvaluationGrid",
    "EventSink",
    "ExperimentTracker",
    "GaussianNLLLoss",
    "IntervalCoverage",
    "Likelihood",
    "LoaderFactory",
    "Loss",
    "MetricRequirements",
    "MetricSource",
    "NegativeLogLikelihoodLoss",
    "OptimizationMode",
    "Optimizer",
    "ParameterRole",
    "PointContinuousRankedProbabilityScore",
    "PredictionInterval",
    "PredictionLoss",
    "PredictiveDistribution",
    "PyTree",
    "RootMeanSquaredError",
    "SquaredErrorLoss",
    "StageResult",
    "StageState",
    "Step",
    "TrainingEvent",
    "TrainingStage",
    "TrainingState",
    "ValidationResult",
    "ValidationStrategy",
    "WeightedSpread",
    "add_epsilon",
    "cdf",
    "coverage",
    "crps",
    "point_crps",
    "rmse",
    "validate_transition",
    "wsu",
]
